### ISSUE TITLE
Programmer bot bitcoin

### ISSUE THREAD

**Issue by wsport2** [ctubio/Krypto-trading-bot#1030]
Good morning, I am looking for a high frequency bot like this for buying and selling bitcoin but I don't have enough knowledge to install it, configure it, etc. I would like to know if someone from the community can help me. The work would of course be remunerated according to the agreed conditions. It is urgent, you will need an answer as soon as possible. Thank you

Buenos días, estoy buscando un bot de alta frecuencia como este para la compra y venta de bitcoin pero no tengo el conocimiento suficiente para instalarlo, configurarlo, etc. querría saber si alguien de la comunidad me puede ayudar. El trabajo sería por supuesto renumerado de acuerdo a las condiciones pactadas. Me es urgente, necesitará respuesta lo antes posible. Gracias

**Comment by zanzu** [comment]
Hi,  Thanks for reaching out.  Have you had a chance to review the README?  Perhaps you know this but it goes without saying, after configuring, you’ll need to maintain the operations of the bot.  Are you prepared for that?

**Comment by xloem** [comment]
What we need is public documentation on how to turn a profit: I hear you can make over 1% return a day with the right parameters  I would pay some to help make that documentation happen and I bet others would too.  I'm sure we'd be happy to help wsport2 with install and setup on the sidelines too.

**Comment by ctubio** [comment]
morniiing'''
im sorry for the confusion, if you are looking for community support, consider to join the [irc](https://kiwiirc.com/client/irc.freenode.net:6697/?theme=cli#tradingBot) channel (this is a bug tracker for technical issues).

also, the main bot in K does not enforce any strategy, you are free to configure your own, thats why all options are highly configurable, with opposite values where possible. The idea is that while an human have an strategy in mind, a bot can be configured to work on that especific strategy, and be modified overtime as the human considers (the idea is not to provide a permanently-working-in-all-conditions strategy to a human).

:koala: hope this helps''' (otherwise feel free to add a comment)

**Comment by ctubio** [comment]
:koala: ah yes, i said "the main bot in K" because now is possible to create alternative bots, see [src/bin/hello-world](https://github.com/ctubio/Krypto-trading-bot/tree/master/src/bin/hello-world) folder.

**Comment by wsport2** [comment]
Hi, I going to study the readme and I will say you, thank you for answer

**Comment by wsport2** [comment]
Do you speak spanish? thank you

**Comment by ctubio** [comment]
:koala: yes, and catalan also; but ppl tends to speak english here so everybody can understand it

**Comment by wsport2** [comment]
Estoy creando una empresa de trading y necesitaría poder hablar contigo
personalmente para ver si pudiéramos tener tu bot operativo y llegar a un
acuerdo, habría posibilidad de hablar contigo por teléfono, zoom o skype?
Gracias.

**Comment by ctubio** [comment]
:koala: no estoy interesado en hacer ninguna entrevista telematica, pero puedo responder a cualquier pregunta que tengas por escrito.

:bulb: si consideras crear una empresa basada en la ejecucion de software lo normal seria tener mas de un programador en plantilla.
