### ISSUE TITLE
Unable to fetch data from BITMEX for symbols XBT/USD

### ISSUE THREAD

**Issue by kevinvoswebdevelop** [ctubio/Krypto-trading-bot#1064]
I can't start the trading bot because of the following error:
Errrror: Unable to fetch data from BITMEX for symbols XBT/USD, response was: {"object":[]}.

Please help. I have provided the right api keys in the file K.sh.

**Comment by ctubio** [comment]
morniiing'''
maybe there was an issue fetching https://www.bitmex.com/api/v1/instrument?symbol=XBTUSD and you end up with an empty handshake; if you agree you can try:
```
rm -rf /var/lib/K/cache/handshake.BITMEX.XBT.USD.json
```
and restart the bot again
(otherwise the cached file will expire in 7 hours)

the timeout for api calls is set to 21 seconds, you can check how long it takes to fetch data from your computer with something like (in case you are still unable to fetch data from XBT/USD on BITMEX):
```
time curl https://www.bitmex.com/api/v1/instrument?symbol=XBTUSD
```
or use `--latency` argument

:koala: hope thiz helps'¡ (let me close the issue cos for me is fine BITMEX on XBT/USD, but feel free to further comment if you consider)

**Comment by kevinvoswebdevelop** [comment]
@ctubio I have even tried with the --nocache and --without-ssl flags (and also , but still getting the same error. My system is Ubuntu 20.04.02 LTS.

When I execute your time curl command, I get a good response within milliseconds. Something funny is going on here but I can't seem to pinpoint the problem...

**Comment by ctubio** [comment]
:koala: im not sure how to reproduce it but i will try a few things :S

**Comment by kevinvoswebdevelop** [comment]
@ctubio Is the URL correct you use at line 661 in lib/Krypto.ninja-apis.h? Because I think base outputs "BTC" instead of "XTD", which is why you return "XTD" hardcoded underneath. Or am I wrong?

**Comment by kevinvoswebdevelop** [comment]
Foolish me, I had BTC/USD in my K.sh which should have been XBT/USD. Sorry for that haha.

**Comment by ctubio** [comment]
:koala: thanks for the info'¡
