### ISSUE TITLE
Bitfinex API Dying Causes Stuck Bot

### ISSUE THREAD

**Issue by MiningInMySleep** [ctubio/Krypto-trading-bot#1070]
Happened just now.
Is there any way we can detect this and auto-restart the quoting engine? That fixed it for me.
Edit: To clarify, stuck bot means orders are stuck on web UI but not visible on exchange (same as random disconnect issue).

**Comment by flfsbr** [comment]
The same is happening to me at Binance. It happens a moment when the bot sends orders and receives an insufficient balance response (even with a balance in the wallet). So the bot keeps sending orders repeatedly and I end up taking IP ban for excess orders sent. I have to keep looking at the console constantly because this has been happening every hour or so.

**Comment by ctubio** [comment]
do you have a message like:
```
 GW WHATEVER Quoting state changed to DISCONNECTED.
```
if so, we could cancel&clean current orders; otherwise im not sure how to detect this

**Comment by MiningInMySleep** [comment]
> 🐨 maaaybe yes, if you have a message like:
> 
> ```
>  GW WHATEVER Quoting state changed to DISCONNECTED.
> ...
>  GW WHATEVER Quoting state changed to CONNECTED.
> ```
> 
> if so, we could cancel&clean current orders; otherwise im not sure how to detect this
> 
> do you have this msgs?

I honestly can't remember, but I'll keep an eye out if it happens again and get back to you.

**Comment by ctubio** [comment]
this will be fixed together with https://github.com/ctubio/Krypto-trading-bot/issues/1056, just have enabled cxl in the UI if the api is unstable for you, it now cleans local as well as remote orders
