### ISSUE TITLE
How to add new gateway/exchange?

### ISSUE THREAD

**Issue by wulabs** [ctubio/Krypto-trading-bot#141]
I am using your latest code (commit c5dea2e902ec5ae49e0095b5da39fadd6bd0baed), where gateways are not in js.

How do I add a new gateway/exchange? It seems all the gateway code was moved into a precompiled library (https://github.com/ctubio/Krypto-trading-bot/commit/962131a3b030b107b1f341025448479d0aee8828). Is there a way to have those exposed?  I plan to add okex so hopefully it is not much change from okcoin.

**Comment by ctubio** [comment]
are you askign how to code? use your keyboard

**Comment by wulabs** [comment]
No, I'm asking for  src/lib/g0.h through src/lib/g6.h to be added back into the repo. We are not able to extend and/or collaborate on development if the source is removed into a precompiled library.

**Comment by ctubio** [comment]
isnt it obvious?

you can get these from the history of commits; you are able to do all you want with your keyboard; i never asked for a collaborator; the precompiled library is to allow moar users to use the app; the removal is because nobody helped me while i develop the thousands lines and i get tired of working for free for you all
