### ISSUE TITLE
Nothing happening

### ISSUE THREAD

**Issue by Laurensvandendriessche** [ctubio/Krypto-trading-bot#188]
Evening,

after some struggling I finally got the bot running in a docker container. The bot is connected to the hitBtc exchange and I'm using the default settings.

For what I notice, I get very unstable behaviour in the bot:
- No quotes generated
- Orders open in hitBtc that are not displayed in the ui
- No trading at all taking place
- Order book not streaming

I find it very hard to describe what is going on/wrong. I did some tweaking of all parameters after reading the manual without success. I even joined the irc channel, but had no response.

Could it be that there are some issues connecting to the hitBtc exchange and do you advise against using it?

Thanks for your time.

L. Vandendriessche

**Comment by ctubio** [comment]
is strange that the bot can send orders to the exchange but cannot read market data.

usualy the api key is wrong, so market data is all OK but orders fail to be placed.

im not sure what may be wrong for your bot to not be able to read market data, can you please validate that you have this line in the config file?:
```
    "HitBtcMarketDataUrl": "ws://api.hitbtc.com:80",
```

im sure you have it :( so im sure that im not sure what may be wrong :(

otherwise, what i would suggest, is to collect some logs while running the app in thje foreground with `node K` and see if there is any interesting message pointing to the cause of the issue.
