### ISSUE TITLE
How i can stop the bot....

### ISSUE THREAD

**Issue by Ultrahoschie** [ctubio/Krypto-trading-bot#221]
Hey...
when i will stop the bot with .... make stop or make stopall .... this Message is showing ....

t@debian-jessie-1:~/K# make stopall           
ls -1 etc/*.json etc/*.png | cut -d / -f2 | cut -
d . -f1 | grep -v ^_ | xargs -I % make KCONFIG=% 
stop -s                                          
ls: cannot access etc/*.png: No such file or dire
ctory                                            
There are several suitable screens on:           
        24427.K (09/14/2017 05:32:42 PM)        (
Detached)                                        
        23862.K (09/14/2017 05:31:50 PM)        (
Detached)                                        
        30692.K (09/14/2017 03:33:53 PM)        (
Detached)                                        
        30643.K (09/14/2017 03:31:14 PM)        (
Detached)                                        
Use -S to specify a session.              

Thx

**Comment by ctubio** [comment]
try `killall screen` or you can reattach each screen with:
screen -r 24427.K
screen -r 23862.K
screen -r 30692.K
screen -r 30643.K
and then ctrl+c on each

in latest commits i added a condition to `make start` to avoid duplicated bots, are you running the latest commit? otherwise this could happened if you run multiple times `make start`. in  latest commit to avoid this situation it does:
```
 $ make start
START K DONE

 $ make start
K is already running..
```
