### ISSUE TITLE
Hello *.sh files

### ISSUE THREAD

**Issue by ctubio** [ctubio/Krypto-trading-bot#231]
**Where?**
`./etc/*.json` do not exists anymore, instead we have `./*.sh` files.

**What?**
all configs are now arguments instead, hardcoded into `./*.sh` files.
on install `dist/K.sh.dist` is moved to `./K.sh` (it allows easy execution of customizable filenames using TTY autocomplete)

**When?**
since https://github.com/ctubio/Krypto-trading-bot/commit/29e68e9feedced0020609c81e0d58af32a8d169b, do not upgrade until you are ready to rewrite your config files

**Why?**
trying to kill all json objects, because json is so slow

![giphy-downsized](https://user-images.githubusercontent.com/1634027/30592487-3c599764-9d47-11e7-93e3-53f45c309048.gif)

**Comment by Camille92** [comment]
Ohhh man I'm so lazy to do that, but will get to it! haha

**Comment by b-seite** [comment]
Hey Charles,
in my K root folder i have two config files. One is K.sh and one is K-ethusd.sh.
I did a make latest and my K.sh was overwritten with the dist one. I found that in the output from the make command: 
make[4]: Leaving directory '/home/ubuntu/K'
test -f *.sh || (cp dist/K.sh.dist K.sh && chmod +x K.sh)
/bin/sh: 1: test: K-ethusd.sh: unexpected operator.
seems that the test result is false due to the message?
Any idea?

**Comment by ctubio** [comment]
im sorry i wrote shit, that `test` fails if multiple *.sh exists, soOn i will commit ` test -n "`ls *.sh 2>/dev/null`"  || (cp dist/K.sh.dist K.sh && chmod +x K.sh)` but i cannot do it right now, feel free to manually use this replacement meanwhile

**Comment by ctubio** [comment]
hope the installation steps are fixed after the last commit
