### ISSUE TITLE
GDAX sandbox

### ISSUE THREAD

**Issue by usovichivan** [ctubio/Krypto-trading-bot#266]
Hi.
Does it possible to use bot with GDAX sandbox account?
I tried, but keep getting a message "COINBASE FIX Logout"

Is there a way to have a fake balance on any exchange to test a bot? I tried to set OrderDestination as NULL, but it does't effect on balance. 

Thanks in advance.

13:09:24.554632 DB /data/db/K.3.BTC.USD.db loaded OK.
13:09:24.557460 DB loaded Quoting Parameters OR reading defaults instead.
13:09:24.557733 DB loaded 0 historical Trades.
13:09:24.558127 DB loaded 0 STDEV Periods.
13:09:24.558384 DB loaded EWMA Long = 47155.96000000.
13:09:24.558497 DB loaded EWMA Medium = 0.00000000.
13:09:24.558579 DB loaded EWMA Short = 0.00000000.
13:09:24.558769 DB loaded TBP = 0.00116376 BTC.
13:09:25.399046 GW COINBASE WS Streaming book levels.
13:09:25.896693 GW COINBASE FIX Logout.
13:09:38.402315 UI authorization success from ::ffff:
13:09:40.233606 UI 1 currently connected, last connection was from ::ffff:.
13:09:46.939623 GW COINBASE FIX Logout.
13:10:07.957322 GW COINBASE FIX Logout.

**Comment by ctubio** [comment]
im sorry i think is not possible since we use FIX protocol.

in Websocket protocol of gdax there is a sandbox, but we only use the websocket to collect market levels.

orders are send to FIX protocol of gdax, so all orders will be real even if the market levels are fake coming from the sandbox.

That was possible before FIX protocol implementation, because all gdax communication were throw websocket protocol. im not sure but you may want to use some really old commit (like from 1 year ago)
