### ISSUE TITLE
GDAX Bot 'stops' with no error message

### ISSUE THREAD

**Issue by CarlitoGrey** [ctubio/Krypto-trading-bot#283]
Had this a couple of times now, I think always on GDAX. The bot seems to just stop updating with no error messages. The stats UI still works, it just shows the same value. 

You can see the bot on the left has stopped:
![image](https://user-images.githubusercontent.com/29517455/31310136-9fea45fc-ab8a-11e7-8ce0-d62e1d17b3ed.png)

**Comment by ctubio** [comment]
for me it fails with red background like in https://github.com/ctubio/Krypto-trading-bot/issues/270; not sure if i was able to reproduce this yet

**Comment by b-seite** [comment]
Hi all,
at the moment and with the latest commits i have the same issue: After some minutes or hours of working normal the bot stops working with a red background. No error is thrown. It happens quiet often at the moment. 
Any ideas?

**Comment by jhoff10** [comment]
I also have the exact same problem.  I just downloaded the software and was assuming it was something on my end!  I'll see if I can figure out what could cause this... it'll be a good way for me to get a feel for the software.

**Comment by jhoff10** [comment]
It turns out GDAX automatically terminates the connection after a period of time.  Someone on [this link](https://github.com/coinbase/gdax-node/issues/104) used this workaround.  I don't have much time, but I'm gonna see if I can get my bearings with the code and integrate this later this week.  If someone else wants to do this earlier, they're welcome to.

Here's the fix

// if it closes reconnect
websocket_client.on('close', (data) => {
    log_message('ERROR', 'Websocket Error', `websocket closed unexpectedly with data: ${data}. Attempting to re-connect.`);

    // try to re-connect the first time...
    websocket_client.connect();
    
    let count = 1;
    // attempt to re-connect every 30 seconds.
    // TODO: maybe use an exponential backoff instead
    const interval = setInterval(() => {
        if (!websocket_client.socket) {
            count++;
            
            // send me a email if it keeps failing every 30/2 = 15 minutes
            if (count % 30 === 0) {
                const time_since = 30 * count;
                log_message('CRIT', 'Websocket Error', `Attempting to re-connect for the ${count} time. It has been ${time_since} seconds since we lost connection.`);
            }
            websocket_client.connect();
        }
        else {
            clearInterval(interval);
        }
    }, 30000);
});


PS Ctubio, if possible, can you add me to the unlocked version of the software?  My bitcoin address is 13Kp3vLshY2fwCBEsHD84VEL5J2MtdGAy9, should I purchase the software from you and then receive a refund, or can you enable me for the unlocked version on your own?

**Comment by ctubio** [comment]
im still not able to reproduce this, if you ask me the official gdax website stops responding after a few hours but the UI of K keeps responding as normal; libquickfix have its own reconnect after 21 seconds (we dont use that boooriiing nodejs library)

**Comment by ctubio** [comment]
feel free to open a new issue if this still happens to you, im running gdax 24/7 so i hope i must notice too if it ever happens

**Comment by ctubio** [comment]
sorry i didnt read last paragraph; all info to unlock the bot is in the readme; feel free to join the IRC for questions
