### ISSUE TITLE
High CPU Usage

### ISSUE THREAD

**Issue by CarlitoGrey** [ctubio/Krypto-trading-bot#30]
This is seen alongside high main loop wait times and high order latency (>1s). 

![image](https://user-images.githubusercontent.com/29517455/27654530-549ae04c-5c3a-11e7-94e8-1913229cebcc.png)

**Comment by CarlitoGrey** [comment]
Restarting K seems to resolve the issue.

**Comment by ctubio** [comment]
i just send mongodb to the fucking hell xD

**Comment by ctubio** [comment]
feel free to donate if you enjoy the commit; it took me to fix more than what i enjoyed

**Comment by b-seite** [comment]
Hi Charles,

first of all thank you for the hours of work. The tool is great and is doing it´s job very well.
but from time to time i have the problem again with high cpu load and high latency around 100ms.
it starts one to two ours after a restart that the cpu load and the latency goes up. After restart K i have latencies of 0-3ms. 
Do you have any ideas?

Trading on GDAX and using latest commit (but the error occurred at least since 3 days) and Ubuntu 16.04 with node.js 8.1.2

![bildschirmfoto 2017-07-11 um 12 33 28](https://user-images.githubusercontent.com/540850/28064651-ccddf580-6635-11e7-8c1c-3e578b41ecb8.png)

**Comment by ctubio** [comment]
yea, thats why im rewriting everything; to increase performance and get rid of all shitty codes
