### ISSUE TITLE
Can't get EWMA to work

### ISSUE THREAD

**Issue by deeepen** [ctubio/Krypto-trading-bot#312]
I'm trying to get the technical analysis portion of the trading strategies to work but it only trades in one direction. 

I've tried almost everything I can think of for the LONG and SHORT values. I've read various "genius post" issues on this board but I can't figure this out. 

It just says TBPHeld for the sell side and continues to buy on one side. 

I'm using AK47 with 2 bullets. I'm watching the STATS chart directly from the program and I see the LONG numbers and line over the SHORT number and line but it continues to buy even though it should be selling. 

I've tried various values - 50 long, 10 short or 5 long, 3 short or 26 long, 12 short but it just trades in one direction. 

I've changed the sensibility to 0.01 to 1 and also modified the pDiv from 0.01 to 1 and sometimes more but it's not working. 

Also I've run "make latest" and compiled for the most recent version of the software. 

SOP is disabled. I've tried different Ranges for ping pong width - currently at 0.10 for both sides. Trading on GDAX.  APR is off. 

How many minutes does the EWMA need before it trades on it's signal? Are there any other things I'm missing?

**Comment by Camille92** [comment]
send a picture of your settings please, it would help to help.

**Comment by ctubio** [comment]
consider to look at the Stats link, there is graphics there where you can visualy answer your TBPHeld questions

**Comment by deeepen** [comment]
@ctubio, @Camille92 - I have been using the Stats link to validate the correct actions but it doesn't appear to be working?

Here's a screenshot.

<img width="1919" alt="2017-10-19_1935" src="https://user-images.githubusercontent.com/351834/31787957-23caa73a-b505-11e7-8ce8-0f5a1180f6e8.png">

**Comment by deeepen** [comment]
@Camille92, @ctubio - Here's an example screenshot where the SHORT has crossed above the LONG, shouldn't it be selling?

Your help is appreciated for this AWESOME software.

<img width="1919" alt="2017-10-19_1935" src="https://user-images.githubusercontent.com/351834/31788018-5320424c-b505-11e7-85c3-972434ebdf5d.png">

**Comment by deeepen** [comment]
@Camille92, @ctubio - Here's an example screenshot where the SHORT has crossed above the LONG, shouldn't it be selling?

Your help is appreciated for this AWESOME software.

<img width="1919" alt="2017-10-19_1935" src="https://user-images.githubusercontent.com/351834/31788059-7a0ce6a8-b505-11e7-9153-db282dd3e057.png">

**Comment by Camille92** [comment]
Hi @deeepen ,

I had a look at the picture without the blurred part (and thanks to that, I have the explanation).

Your problem is that you have a very important capital and very short ewma and as well as a very small bidSize.

So the first thing you need to know -> if ewma short = ewma long then your target base position (objective) is 50% fiat and 50% btc.

And only if ewma short if above ewma long by sensibility then tbp is 100% btc.
Inversely if ewma short is below ewma long by sensibility then tbp is 100 fiat.

Sensibility is a value in % so 1 is 1%, 0.4 is 0.4%

So with ewma long of 4mn and ewma short of 2mn, you never reach that.

Again, you make buys of 0.02 btc and given your stack it's going to take forever to reach a tbp of around 50% that you must have according to the settings i read.


Finally, I don't know your knowledge of the bitcoin world/trading/market making but given your stack, I really don't think it's the best bot for you (or maybe not in this exact form).

You can reach me on the irc of the bot if you want to talk privately.

Camille

**Comment by CarlitoGrey** [comment]
Camille, by default when short=long the bot holds 50%, I think this should be configurable. It's something I almost always change, what do you think?

**Comment by deeepen** [comment]
@Camille92, Thanks for your insight.  

Is there no way to set the max amount I want traded and have the bot work off of those numbers - so if I set a max of 1 BTC, it only uses 1 BTC?
Also, is there another bot that you recommend if this isn't the one for me?

Thanks.
