### ISSUE TITLE
Unhandled rejection! if exchange is offline or api saturated

### ISSUE THREAD

**Issue by amexperts** [ctubio/Krypto-trading-bot#34]
Running on Mac OSX after having no luck on linux (debian & ubuntu).
But getting the following error:

`Unhandled rejection! TypeError: symbolDetails[Symbol.iterator] is not a function
    at Object.<anonymous> (/Users/adam/Dropbox/Work/Crypto/krypto/app/server/gateways/bitfinex.js:474:21)`

any ideas?

**Comment by ctubio** [comment]
this error means that https://api.bitfinex.com/v1/symbols_details was not accessible at the time of starting the app. a retry will fix it because https://api.bitfinex.com/v1/symbols_details is effectively accessible; so this may be a temporal connectivity issue.

i will try to add a better human readable message, but we can't do nothing else than just retry if https://api.bitfinex.com/v1/symbols_details suddenly returns a blank page.

**Comment by ctubio** [comment]
soOn the gateways will be replaced with a bit of luck (will not invest time in the current js files)
