### ISSUE TITLE
Disconnected. 

### ISSUE THREAD

**Issue by pimbolilu** [ctubio/Krypto-trading-bot#39]
Hi, 

after editing my conf file, I started the bot but I always get this message on the webpage:

Disconnected.
README - MANUAL - SOURCE - changeTheme(DARK) -  -  -  - 0 - MATRYOSHKA - CREATE ISSUE - IRC

What is the problem? :/

**Comment by amoscatelli1** [comment]
If you put this: 
"start": "npm run test-compile && forever start --uid $npm_package_config_config --minUptime 2000 --spinSleepTime 2000 -a -l /path-to-your-K-install-FOLDER/runlog.log K.js $npm_package_config_config && exec npm run test-stunnel",
to the line 103 of package.json and rerun, you will probably see the same message that i've got. 
I'm waiting Camille92's npm install guidelines to resolve.
Regards, A.

**Comment by Camille92** [comment]
@amoscatelli1 published

**Comment by ctubio** [comment]
Hello @pimbolilu,
if you run the app with `nodejs K.js`instead of `npm start` you should see some log lines; can you please paste this log lines?

The Disconnected message means that K client is disconnected from K server, mostly possible because K server is not running (it was running as you can see the page, but it may had crash little after; see the logs with `nodejs K.js` to see the reason)
