### ISSUE TITLE
Trailing Stop or Take Profit (Without EMA and ANALYSIS)

### ISSUE THREAD

**Issue by donaldforest** [ctubio/Krypto-trading-bot#424]
Idea: we make ping and follow trend with some step, if trend go back for some value we make pong.
A necessary condition is to exceed first step value..

Better than text explain this my illustration (the values do not so match with the chart):
![ts_or_tp](https://user-images.githubusercontent.com/33358791/33186731-fcb99238-d09c-11e7-8517-93737dbe260e.png)

**Comment by Camille92** [comment]
I like it but how do you define your first buy?

And what about adding?

**Comment by donaldforest** [comment]
This is popular trade strategy or just second part of strategy. Here is no info about buy.
About "how do you define your first buy" it can be any ping you want.
But you already using K bot and looks like must to know how to buy! ;)

**Comment by Camille92** [comment]
Yes, sure we discussed something vaguely similar here.

I think it's a good idea, but it needs more definition in to be applicable to the bot.

So let's say you define your buy signal with your TBP and ema crossing.
Do you count the buy at the average of the buys you made, the first buy you made or the lowest point of the market?

For the top do you use the highest traded point or an average or a short average to protect you against spikes?

If it goes down and up again before you sold everything, should you still be selling or buying more now?

I don't want to discourage you because it's a good idea, but to be able to automize it and let the bot run for you, we need to think about all the possible outcomes and what to take into account.

**Comment by donaldforest** [comment]
Is to many indicators to made buy. All indicators looks like magick!
As I told before best choice is not indicators, is Martingale: https://github.com/ctubio/Krypto-trading-bot/issues/420
No one bothers make first buy by Martingale using ema + bolinger indicators. Its will work slower but better and with some 5% safer.
+ We always can using stoplosses when we buy even randomly and price go down.

**Comment by Camille92** [comment]
So you just buy and wait for the price to go up or down?

**Comment by donaldforest** [comment]
Its just solution how you can sell with good price without any magic indicator.
How to work K bot?! As I see K buy and wait when price go up. In my case wait more than 24 hours. But in my example we can to squeeze more in case trend go up more optimistic! Something like **sop**. But I could be wrong, because I still not sure how is K choose sell or not sell!

**Comment by DannyGreen** [comment]
Before i found K i was originally looking for a bot that uses this method so +1 from me, as for buying could we not use the same method but in reverse? As for the steps ideally we could use either a percentage increase or a price increase. Maybe also have separate % & price values for the decrease too?
