### ISSUE TITLE
Unable to compute tbp [ qp | pos ] = [ true | false ]

### ISSUE THREAD

**Issue by lejacobroy** [ctubio/Krypto-trading-bot#45]
Hi! I'm running on Mac OS and the bot starts fine, the WebGUi is up but it says 'Disconnected" on bidSize, bidPrice, askSize, askPrice.
Also, when I start it `node K.js`, after a few minutes I get this error : `Unable to compute tbp [ qp | pos ] = [ true | false ]`

thanks!

**Comment by ctubio** [comment]
morninig''
this log message means that the bot can't connect to the exchange to get the wallet positions, mostly possible because the exchange was offline/saturated; in what exchange this was? (if was gdax, note that gdax has been offline 1 every 2 days for a few minutes/hours since a few weeks ago)

if you see that it can't get wallet positions on boot, may be because the exchange is offline, a restart once the exchange comes back is the fix.

i believe you mean exactly https://github.com/ctubio/Krypto-trading-bot/issues/34 but you were not en Bifinex i think; what was your exchange?

**Comment by lejacobroy** [comment]
Thanks!
Yes I am on Bitfinex, the problem was that I had no currency to trade. I thought it would still show some value and the recent trades but no. Once I added funds to the currency I was trying to trade, the bot started.

Great work btw!!

**Comment by ctubio** [comment]
oh, many thanks for the info, will try to control that situation somehow someday
