### ISSUE TITLE
Error binding service gdax stream

### ISSUE THREAD

**Issue by pha3z** [ctubio/Krypto-trading-bot#495]
It worked with default configuration.  Then, I changed the API configuration variables in the K.sh file to use coinbase and my API credentials.  After doing that, I start it and get the following error:

Error binding service [gdax_stream] to 0.0.0.0:4199
bind: Address already in use (98)

Anybody know what may be causing this?  I used netstat to see if another process was using this port before running "make start" in the Kryptobot folder.  No other processes are using this port.

Is there a bug that causes Kryptobot to attempt to bind to the same port twice?  I haven't looked at the code yet.  I wanted to know if anyone else has seen this error first.

**Comment by ctubio** [comment]
that is not a error mesage from the bot; that is from stunnel

make sure `stunnel` is not running before the bot runs.

the bot automaticaly runs `stunnel`, and restart it if is already running.
if the port is already in use is because is already running and if cannot be restarted is because is running with a different user; so kill it and let the bot run it (the bot should not be run with root perms)

**Comment by pha3z** [comment]
After much Googling and system analysis, I gave up.  I was using Amazon Linux 2.  I think the problem is specific to that distro somehow.
