### ISSUE TITLE
BitFinex Api Call Not working

### ISSUE THREAD

**Issue by Juelcf** [ctubio/Krypto-trading-bot#496]
Hi.

The BITFINEX api is not working. 

API_HTTP_ENDPOINT=https://api.bitfinex.com/v2
API_WSS_ENDPOINT=wss://api.bitfinex.com/ws/2

It seems the app is not adding the t required before the Symbol.

Incorrect Call
Call: https://api.bitfinex.com/v2/ticker/BTCUSD
Res: ["error",10020,"symbol: invalid"]

Correct Call
Call: https://api.bitfinex.com/v2/ticker/tBTCUSD
Res: [16853,55.67364556,16863,37.41143219,206,0.0124,16867,66980.5311112,17709,15500]

Easy to fix?

K build x86_64-linux-gnu 2017-12-21 03:11:17.
K version 0day.
04:07:09.244485 DB /data/db/K.BITFINEX.BTC.USD.db loaded OK.
04:07:09.244996 UI ready over HTTPS on external port 3000.
04:07:09.255578 QP Warrrrning: using default values for Quoting Parameters.
04:07:09.271929 DB loaded 0 historical Trades.
04:07:09.286924 DB loaded 0 STDEV Periods.
04:07:09.313014 DB loaded TBP = 0.00000000 BTC.
04:07:09.895215 CF Errrror: Unable to fetch data from BITFINEX symbol "btcusd", possible error message: {}.
K crashed with exit code 1.. Respawning..

**Comment by ctubio** [comment]
the app does not magicaly integrate with new endpoints

is `API_HTTP_ENDPOINT=https://api.bitfinex.com/v1` as in https://github.com/ctubio/Krypto-trading-bot/blob/master/etc/K.sh.dist#L92

**Comment by Juelcf** [comment]
https://api.bitfinex.com/v1 is closed!

Error 404!

**Comment by ctubio** [comment]
yea well, what if you try a correct url of an existent page? all web servers in this world throw a 404 if the page doesnt exists

or simply let the bot connect to a correct url for you using default configs?

if you insist, check this out and blow your mind https://api.bitfinex.com/v1/pubticker/btcusd

next, go to https://docs.bitfinex.com/v1/docs/public-endpoints and play with any shit you want; instead of scream to me

**Comment by ctubio** [comment]
do you really thing that the bot uses simply the urls defined in the config? without appending paths without injecting variables? wtf
