### ISSUE TITLE
Quitting cancels ALL trades, including ones which may have been placed by the user in other software

### ISSUE THREAD

**Issue by jokester01au** [ctubio/Krypto-trading-bot#500]
it should be relatively easy to fix this: just cancel the orders that we actually made.

I realise that this is a safety mechanism in case there is some glitch; perhaps we could have a couple of modes for it: 
   - delete all
   - delete mine

or so.

**Comment by ctubio** [comment]
in what exchange? (just for curiosity because:)

in coinbase there is no way since fix protocol cancels all orders on connect and on disconnect

about the 5min timer it could be modified to allow "delete mine" only, but the propose of it is to delete orders that are not "mine" (cos are zombies) as you said.

so:
"delete all each 5min" is the 5min timer of cxl quoting parameter
"delete all on connect/disconnet" only affects some exchanges, and the ones affected cannot be modified
"delete mine" is the normal functionality of the bot

**Comment by ctubio** [comment]
i hate when gdax cancels my manual orders
