### ISSUE TITLE
hitBTC -  wGet failed Peer certificate cannot be authenticated with given CA certificates

### ISSUE THREAD

**Issue by lumaform** [ctubio/Krypto-trading-bot#503]
It seems like there is an issue obtaining hitBTC's CA certificates. Upon running K, I get the following error:

DB loaded TBP = 0.00000000 BTC.

CURL Warrrrning: wGet failed Peer certificate cannot be authenticated with given CA certificates.

CF Errrror: Unable to fetch data from HITBTC symbol "BTCUSD", possible error message: {}.

K crashed with exit code 1.. Respawning..

Should I not be seeing the hitBTC's CA certificates under /etc/ssl/certs?'

Thanks

**Comment by ctubio** [comment]
i may be wrong but hitbtc i think uses /etc/ssl/certs/COMODO_ECC_Certification_Authority.pem

can you see if upgrading your system openssl to the lest version solves your problem?

otherwise if you are using Debian try https://manpages.debian.org/stretch/ca-certificates/update-ca-certificates.8.en.html

it may be also that the URL is wrong, double check API_HTTP_ENDPOINT is as expected

**Comment by lumaform** [comment]
Hi there. It's CentOS 7. Prior to installing K, I've performed yum update so all packages should be good to go. When I issue curl -v https://api.hitbtc.com, there is no SSL certificate issue. But when I run K, I get the "apt-get update && apt-get upgrade". I've tried the git and zip method of installation and both result in the same error. I wonder if this is a CentOS specific issue.

**Comment by lumaform** [comment]
I think it's CentOS related. I just installed Debian and the installation worked without a flaw and I was able to get K running...

**Comment by ctubio** [comment]
many thanks for the information''

**Comment by ctubio** [comment]
ima try to fix it with https://curl.haxx.se/libcurl/c/CURLOPT_CAINFO.html
