### ISSUE TITLE
Rate Limit - Bitfinex

### ISSUE THREAD

**Issue by renkcub** [ctubio/Krypto-trading-bot#52]
Getting rate limited on Bitfinex.

Not sure UI Rate is enough to reduce. Any other way to "slow down" the bot?

**Comment by ctubio** [comment]
not currently

**Comment by renkcub** [comment]
Still interested in a solution for this. Looking to slow down bot by significant amount and preferably controllable by setting. Perhaps a max orders/sec or MS rate. Bitfinex has a cap of 60/90 and there is no way to fit multiple pairs or even one pair on an account with current bot speed.

Tip bounty??

**Comment by ctubio** [comment]
i can try to do it during next 7days for 0.01000000 BTC

**Comment by ctubio** [comment]
the configurable value should be "orders/second"?

**Comment by renkcub** [comment]
Yes, that works. I'll send the tip.

**Comment by Camille92** [comment]
Hi @renkcub I'm on all the pairs at Bitfi and I don't have your issue.

I do get rate limited on Bitfi's website but the bots keep on working without issue! :)

**Comment by renkcub** [comment]
@Camille92 Thanks for reply. Are you using a single Account, or a single IP? Or multiple of both/either?

Strange I am facing the issue. But it seems to definitely be exceeding rate on just one pair. Perhaps you are using a much higher width and not having orders move as often?

**Comment by Camille92** [comment]
Hi,

I do use stdev protection with bw which in turn limits the number of orders sent to the market.
I use 1 account with 3 ip and one api key per pair.
I was using the same key before and I was limited but by changing it to one key per pair now it's perfect!  :)

**Comment by renkcub** [comment]
I see,
From what I can tell, stdev limits orders from being sent that violate a rolling deviation from recent prices, based on either top, or best/bid ask. This is a good feature, but I don't use it as I'd rather just stay inside the book at all times to a certain extent (although this risks being forward manipulated and frontrunned)

Would you agree?

I did think the BW feature looked interesting also, although Ctubio referenced that it might actually speed up or strain the bot further, so I'm still not sure on the exacts of how these functionalities slow down your bot.

I believe you have accomplished slowdown but would still like this feature, as I don't really plan to use either StDev or BW at this time...

Great feedback tho!

**Comment by Camille92** [comment]
Well everyone has its own trading strategy so if you do good without stdev, perfect :).
For BW it's a simple feature that adapts your order to the book so you're right above/below the next order.


I just stepped in because I don't understand where you can see that you're being rate limited. I see that on my computer when I look at bitfinex.com but I don't think it has any influence on K trading. (I don't notice a difference in the pairs I trade).

And I don't understand the solution of being slower, you're just going to be outrun by the other participants no?

That being said, I'm just very curious about what you expect from that!

Best,
Camille

**Comment by ctubio** [comment]
ima proceed anyway with the feature cos is small and i believe have zero negative impact (will make sure or otherwise will not do it ofcourse)

**Comment by renkcub** [comment]
@Camille92 Indeed I will be beat to market by other participants. But, that is an acceptable cost. 

I need a solution to rate limiting without relying on Optional Features such as StDev and BW. And to be controllable. 

I trade with high volume, 0 fees and right inside the market. Small amount but high volume. Sounds like that may differ from your strategy which might be impacting this. But I am not interested in increasing the spread.

Thanks all!

**Comment by Camille92** [comment]
@renkcub no probs I think we're quite in the same category, with small width / big volumes and etc (I also don't have fees on bitfi).

I use a very short period stdev + bb to be sure that I'm not always fighting against someone using K or another bot as well (you know when to bots are on the same market and both put orders 0.01c above the other for forever at the end killing the width).

I guess I don't understand your issue because I'm not being rate limited (or I don't see it).

Good luck anyway :)
