### ISSUE TITLE
EWMA_LS strange behaviour last time

### ISSUE THREAD

**Issue by donaldforest** [ctubio/Krypto-trading-bot#523]
Hello!

After changing pDiv settings I received this picture where EWMA Short and EWMA Long (Yellow) swapped places to opposite:
![ewma](https://user-images.githubusercontent.com/33358791/34456929-da3c27e6-edb3-11e7-9cf8-ef9a109c1bbd.PNG)

Interested behaviour of Yellow line (EWMA Long). On this image his value 300+ min. BTW its not first time, when I see similar behaviour for long and very long EWMA lines when i save changes. In previous cases I just add 1 to EWMA long value like 300 and then 301, and EWMA_L make some abnormal curvature.
+ In last releases I noticed big difference of EWMA's values in K if compare it with tradingview. I mean not concrete values (yes I know it can have different input data and calculations), I mean crossing ewma with same values. If on tradingview ewma's with same vales crossed, but on K charts in same time there is nothing like (i can be parallel and far)..

**Comment by donaldforest** [comment]
UPD. Example screen in same time in K admin and trading view chart on same exchange with absolutely same ewma values:
![ewma_k](https://user-images.githubusercontent.com/33358791/34457002-ad50f89a-edb5-11e7-8fe1-d6c08f7ba698.png)
![ewma_tw](https://user-images.githubusercontent.com/33358791/34457005-b446a4d8-edb5-11e7-8704-0cc7f56fbb4d.PNG)

I understand that charts have different axes/proportions but you can see flat on K ewma's..

**Comment by ctubio** [comment]
feel free to make a PR if you can find any error in the calculation of ewma values; is pretty simple calculation; hard to be wrong.

**Comment by donaldforest** [comment]
But last changes in timer or timestamp function could affected on ewma calculation?

**Comment by donaldforest** [comment]
UPD
Just changed apMode from EWMA_LS to Manual and get:
![1111](https://user-images.githubusercontent.com/33358791/34457360-914a0b5a-edbf-11e7-9306-fc8364b12feb.png)
![2222](https://user-images.githubusercontent.com/33358791/34457361-942da07a-edbf-11e7-81bd-30c7d6148d5e.png)

**Comment by b-seite** [comment]
hi @donaldforest 

> It same 3 seconds when I changed long ewma from 320 to 319!!! short ewma dont changed! Why I see this picture when both ewma changed in same time??!!

its because every time you press the `save` button, **all** ewma´s are recalculated from values stored in memory or db. Not only those you changed. Even if you do change nothing.

The main question is why are the values so different to the ones before recalculating.
One Answer could be: The reclac on `save` uses only the last n values defined in the settings. The EWMA function then adds a new value every minute but don't loose the old data completely. It just gets less and less weight for every new value. That means a recalc might be a bit different than a calculation over time.  

hope that helps finding the error

**Comment by donaldforest** [comment]
@b-seite correct EWMA_* only if I push save button every hour or often!

**Comment by b-seite** [comment]
i agree that there is a strange behaviour on EWMA calculation.
this screenshot was made on a bot that runs for several days untouched a minute after save was pressed.
![bildschirmfoto 2018-01-01 um 09 52 49](https://user-images.githubusercontent.com/540850/34466609-05e8a348-eeda-11e7-98fd-05b9ec6f2d7f.png)
i will investigate a bit the next days. 
happy new year🎉

**Comment by Camille92** [comment]
Hi guys,

I think @donaldforest  is right, we're on to something.

I think a possible explanation for the jump we can see on save could be due to different rounding parameters between the 2 ways of calculation.
Is there a way to check that?

Also it might help if we link ewma calculation to the beginning of a minute now and not randomly (so we take the first second of every minute as a referential).


What do you think about that?

best,

Camille
