### ISSUE TITLE
External Notification Support

### ISSUE THREAD

**Issue by werkkrew** [ctubio/Krypto-trading-bot#534]
Similar to the sound checkbox, would be nice to have other methods for notification, perhaps via plugins so implementing different providers could be easy.

For example, pushbullet, irc channel, slack, discord, etc. for when pongs complete or periodic profit notifications.

I might take a look at implementing this and submit a PR for it.

**Comment by ctubio** [comment]
as long as is implemented in the UI no problem; the server is not like going to waste time connecting to more thirty party application interfaces; also this tend to be updated and maintenance of it is also not going to happen; this are private companies that im not interested to support in any way (nor their chain of upgrades because bussines decisions)
