### ISSUE TITLE
Phantom order(s) and stop trading

### ISSUE THREAD

**Issue by donaldforest** [ctubio/Krypto-trading-bot#546]
Sometimes Quotes: 0/1/0 or Quotes: 2/0/0, but is no any order in orders list. Bot stop correct working. cxl? enabled, but isn't help for hours. SSH restart help only.
In my case it was with HitBTC API. Yes, it was often when exchange API work with over-latency, but if "q" or Ctrl+c help reset bot and orders, maybe it possible to toughen with more hardest rules for cxl? ?

**Comment by donaldforest** [comment]
UPD: Looks like troubles on HitBTC in this case. When I try check orders on web side of exchange I see freeze "Loading..." line in "Active Orders (0)" tab. Same on "Filled and Cancelled Orders" tab.
K show "Quotes: 2/0/0" and empty orders in orders table.
Maybe need some alarm stop or bot hard reset in this case? Maybe need some rule like TBP = 0 or TBP = 100 (according user preference) when bot try save depo without checking orderbook data and stop trading to wait when API start working stable for some time (10-30 min of stable data)?

**Comment by donaldforest** [comment]
UPD2: When HitBTC start show "No active orders" in "Active Orders (0)" tab, K continue show Quotes: 2/0/0 and do not make new orders. cxl? - checked. Waiting more than 5 min - now I see order in web interface in "Active Orders (1)" tab, but still "Quotes: 2/0/0" and empty orders table in K interface. I manually cancel order on exchange side and bot start working from this point correctly.

**Comment by serzhiio** [comment]
I have exactly the same situation with HitBTC last days.

6 янв. 2018 г. 11:36 пользователь "donaldforest" <notifications@github.com>
написал:

**Comment by serzhiio** [comment]
I have exactly the same situation with HitBTC last days.

6 янв. 2018 г. 11:36 пользователь "donaldforest" <notifications@github.com>
написал:

Sometimes Quotes: 0/1/0 or Quotes: 1/0/0, but is no any order in orders
list. Bot stop correct working. cxl? enabled, but isn't help for hours. SSH
restart help only.
In my case it was with HitBTC API. Yes, it was often when exchange API work
with over-latency, but if "q" or Ctrl+c help reset bot and orders, maybe it
possible to toughen with more hardest rules for cxl? ?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/ctubio/Krypto-trading-bot/issues/546>, or mute the
thread

**Comment by donaldforest** [comment]
![hitbtc_phantom](https://user-images.githubusercontent.com/33358791/34651512-41e2e0a4-f3e2-11e7-880c-243e2fb0e10f.PNG)

**Comment by ctubio** [comment]
seems all this is on hitbtc, so if you all agree lets take care of it at https://github.com/ctubio/Krypto-trading-bot/issues/550
