### ISSUE TITLE
HitBTC: Quantity not a valid number or not set?

### ISSUE THREAD

**Issue by serzhiio** [ctubio/Krypto-trading-bot#550]
Something new:
09:35:52.105687 GW HITBTC Warrrrning: Ignored response: {"error":{"code":2010,"d                                                                                         escription":"Quantity not a valid number or not set","message":"Quantity not a v                                                                                         alid number"},"id":3,"jsonrpc":"2.0"}.
 WTF?

**Comment by serzhiio** [comment]
Its happening on stuck orders "Quotes: 1/0/0" background.

**Comment by donaldforest** [comment]
Yep. Same here. It in this case bot lost some time to make new orders and work some unusual.

**Comment by ctubio** [comment]
im was not able to reproduce this on hitbtc

in what currency this happened to you?

**Comment by serzhiio** [comment]
btc/usdt

9 янв. 2018 г. 15:31 пользователь "Carles Tubio" <notifications@github.com>
написал:

**Comment by donaldforest** [comment]
In my case **API_CURRENCY=BTC/USD** (HitBTC)

**Comment by ctubio** [comment]
i try hard but was not able to reproduce this; will keep trying but any --debug info you can collect is appreciated :S

**Comment by donaldforest** [comment]
> im was not able to reproduce this on hitbtc

@ctubio for test try **/sec** = 1

**Comment by ctubio** [comment]
i usualy have several trades at 60 sec; you mean 1 trade 1 sec? xD

**Comment by donaldforest** [comment]
Nevermind, this isnt help find problem. Sorry!
I mean in setting allow make 1 trade per second without hold. (by default bot have value /sec = 3)

**Comment by captainreptile** [comment]
I had the same issue yesterday:

`04:09:17.101998 GW HITBTC Warrrrning: Ignored response: {"error":{"code":2010,"description":"Quantity not a valid number or not set","message":"Quantity not a valid number"},"id":171,"jsonrpc":"2.0"}.`

Further playing around i noticed that "value" in quotes are always "0.0000" - a usual behavior of K as it seems, and it was working so far - so its must be an issue on HItBtc side.

Further on, I switched to pingpong and issue disappeared and an order was placed succesfully, then switched to AK-47 and issue persisted. after about 30 min issue disappeared at all.
I saw this error again 1 or 2 times since.

I also noticed that when this error appears the "Market Width"  drops down significally almost 0.000
Which i guess means hitbtc is not accepting orders?

**Comment by ctubio** [comment]
may be a new error cos is not listed at https://api.hitbtc.com/#errors

im not seen this warning message, but if it ever happens to me i will consider to do something or add it to the list of ignored msgs

**Comment by donaldforest** [comment]
> 04:09:17.101998 GW HITBTC Warrrrning: Ignored response: {"error":{"code":2010,"description":"Quantity not a valid number or not set","message":"Quantity not a valid number"},"id":171,"jsonrpc":"2.0"}.

Same here. I report about in IRC chat.

**Comment by willinspire** [comment]
I've been getting this error message consistently for the past couple days now:

`{
  "error": {
    "code": 2010,
    "message": "Quantity not a valid number",
    "description": "Quantity not a valid number or not set"
  }
}`

The API documentation located at [https://api.hitbtc.com/#errors](https://api.hitbtc.com/#errors) does not contain the error code included in the HitBTC server's response (i.e. "2010") so I'm really at a loss as to how this can be resolved.

**Comment by DiegoRam** [comment]
> The API documentation located at https://api.hitbtc.com/#errors does not contain the error code included in the HitBTC server's response (i.e. "2010") so I'm really at a loss as to how this can be resolved.

Same happens to me regarding error 2012, there is no doc or reference at all. Sad
