### ISSUE TITLE
Okex many one-time orders

### ISSUE THREAD

**Issue by serzhiio** [ctubio/Krypto-trading-bot#557]
Looks like we didnt get rid of such things. Where is the source of a problem?
BTC/USD market
![okex-one0time-multiple-orders](https://user-images.githubusercontent.com/10449591/34775632-e94132bc-f624-11e7-8a83-6d5a72b7ec17.jpg)

**Comment by serzhiio** [comment]
This problem cause one moment buy of a big (huge) amount of coins.

**Comment by serzhiio** [comment]
another catched
![hitbtc-multiple-orders-another](https://user-images.githubusercontent.com/10449591/34822752-089be422-f6d9-11e7-916e-646964221e5b.jpg)

**Comment by ctubio** [comment]
i saw this also in other exchanges not only in okex; i do think is because bot sends that fast the orders and the exchange simply completed them (note okex is without post-only; if the market was at that price the order would be matched immediately)

the solution to me for okex is having a bigger width, or a bigger trades/sec; not sure if okex have delayed market data like poloniex but i truly hope it does not; if so will care for okex as same as for poloniex

**Comment by serzhiio** [comment]
Can we request order existence before sending a new one? At HitBTC sometimes 2 or more orders executes simultaneously just because exchange accepted all of them. Seems not very good situation.

**Comment by ctubio** [comment]
im rewriting QE::updatedQuote and everything after it, lets hope for it better than add a new api call
