### ISSUE TITLE
HitBTC Zombies

### ISSUE THREAD

**Issue by MiningInMySleep** [ctubio/Krypto-trading-bot#579]
Rebuilt after the last commit on Jan. 15th, but still getting zombie orders on various coins.
I'll try grab some debug logs later tonight after work, but it doesn't seem to just be a one-time thing. They are appearing extremely frequently now.

**Comment by captainreptile** [comment]
i have the latest commit too and since i am having ghost trades: they don't appear in history or in logs but they they do appear in trade history on the exchange website...

**Comment by MiningInMySleep** [comment]
One thing I did notice is that whenever I am able to pull up the online interface and get 2 orders on the same side to show up, the older zombie order has a ridiculously high latency like 7000+. Not sure if that helps, but maybe this is an indicator that the issue is on the HitBTC API server side?

**Comment by CarlitoGrey** [comment]
I spent half the night and a a decent amount of whisky looking at this.
It stems from orders which are 'sent' but not received by the exchange for 40-50 seconds. I say 'sent' because I can't confirm the order left my vps, whether the delay is in the bot, or in hitbtc's infrastructure. 

You can see this in the logs, an order is 'sent' at say 01:30:10, there is a reply at 01:30:50. In the exchange the order is placed at the later time of 01:30:50. 

The reason this is a problem is that 1: by default K assumes if there's no response within 10 seconds that the order is a zombie and K's db is purged of the order information. If the order goes live K then receives a reply but doesn't do anything with it (like cancel it). 

The other is that because the order is processed by the exchange 40 seconds after it was generated, the price may have moved down. In this case a buy order is filled immediately (as a taker), giving the 'ghost' orders. 

Carles, I don't think this is an order book issue anymore. I think some debug output from your private code (when the order is actually sent to uWS may help in working out whether the delay in processing is in K or in the exchange itself.

**Comment by captainreptile** [comment]
@MiningInMySleep Do you have the "cxl?" ticked? i ticked that to close open orders after some minutes - though it may affect depend on the strategy ...

**Comment by captainreptile** [comment]
@CarlitoGrey Much appreciated for the info. i did have ghost orders earlier but now it seems good.

My latest order: 16:26:**17.746522**  and on HitBTC was logged at: 2018-01-17 16:26:**11.403** 
Could be either of us on an offset..

What is the ping between your VPS and HitBTC API?

**Comment by CarlitoGrey** [comment]
@captainreptile < 0.5ms

**Comment by CarlitoGrey** [comment]
Thanks Carles. Like I said we don't know if it's K or HITBTC. I suppose with your exchange code you can log more than I can. 
The only other option is to watch the actual network traffic but I'd have to setup ssl decryption to view it.

**Comment by ctubio** [comment]
lets add some --debug-private; i didnt yet cos was afraid of ppl sharing the logs, but a meanful name may help to avoid it

hope you can then enjoy debugging as me (btw i keep testing hitbtc but no zombies here yet)

**Comment by ctubio** [comment]
cannot cancel replied working orders that do not exists in the memory (cos were already deleted after 10sec as new) cos then all manual orders will be canceled by the bot

also increase the 10 seconds removal of new orders to 1 minute for example doesnt makes lot of sense; (even less sense if looking from the point of view of bitfinex)

im afraid this issue will be closed without any mod soOn

**Comment by ctubio** [comment]
after 48h i still didnt saw any delayed/zombie orders here, so lemme close this but please feel free to comment in here or open new issues if you still consider that hitbtc integration must be improved
