### ISSUE TITLE
Suggestion: allow a fixed "budget" per bot

### ISSUE THREAD

**Issue by Pat71** [ctubio/Krypto-trading-bot#611]
I am using multiple bots on different coins, all on USDT.
The problem is, that e.g. the TBP(%) and the profit calculation is based on the USD, so if one bot buys a lot of coins, the tbp(%) for the other bots gets reduced and vice versa.

It would be nice if there was an option "budget" or similar where you can specify how much of the base currency the bot can use (i.e. "use 500USDT") and all dependant calculations are based on this (like profit).

**Comment by ctubio** [comment]
nice idea many thanks'¡ will do soOn''

**Comment by Pat71** [comment]
wallet-limit does not work (yet) as intended:
I started K with "--wallet-limit=50" on ETCUSD, set tbpand maxbidsize to 10% and the first bid goes with 28$ (maximum should be 5$ if I understood the new option right).
Furthermore, in the "value"-box on the far left the full base currency is printed (I think the wallet-limit should be listed there).

**Comment by ctubio** [comment]
if the market is ETCUSD, --wallet-limit=50 means 50ETC; that is, the bot will not have more than 50ETC on both wallet sides.

the limit is not set to FV*x, FV is used to calculate the USD after the remaining ETC

**Comment by ctubio** [comment]
are you using poloniex?

**Comment by Pat71** [comment]
No, HITBTC.

**Comment by ctubio** [comment]
mm.. what you explained may happen at poloniex cos in poloniex the sides in the wallet of base/quote currencies are opposite.

all other exchanges should work as i said, so if you notice it doesnt must be a bug or a missunderstanding

for sure i can tell the calculation for ask/bidSize when using % was not modified; so if you feel that you bidSize is wrong may be because another reason.

what we modified here is a limit of wallet values. (the possible 100% of available wallet funds used to calculate everything else)

can you maybe show/explain again what is your value for --wallet-limit and what are the wallet values that you see in your balance panel (left)? (i hope we can see then were is the bug/missunderstanding cos i really didnt understood your previous comment)

anyway this afternoOn ima rereview thiz last commit

**Comment by Pat71** [comment]
hm. like you implemented it now: what is the difference to TBP (manual mode)?

What I originally meant in my suggestion was that I specify --wallet-limit=50 (on ETCUSD, for example) and K sets 50$ as limit, i.e. K ""sees" only 50$ and can only spent 50$.
All values (TBP, ask/bidsize%, profit, ...) relate to that value, i.e. in this example, if I specify maxasksize=10%, the maximum ask size is 5$.

This way I could run multiple bots and they don't "interfere" which each other. Example:
I have 200$ in total. I let 4 bots run, each with --wallet-limit=50 (on ETCUSD, BTCUSD, ETHUSD, LTCUSD) and each one runs on its own coin with its separate budget. If one loses all of the 50$ (most unlikely), the others are not affected.

**Comment by ctubio** [comment]
many thanks for the infor, lets reopen this while rereviewing it

**Comment by allenhurff** [comment]
@Pat71 Thanks for this suggestion, as you stated it. 

I want to provide a real world example, I THINK, further supports your example.  If, after reading this, you see I am confused or misinterpreted your issue/comments -- please feel free to call me out with something like "Dude, Apples and Oranges" if I read the content/context wrong.

Since we don't have a "--wallet-limit" concept, one GDAX account cannot trade to USD for **TWO** currency pairings if they use the same destination fiat or coin (BTC to Cash and ETH to cash same gdax account).  For real-world example, I am trading **BTC-USD** AND **ETH-USD** on **GDAX**.  However, I was forced to use **TWO seperate GDAX accounts** SO they isolate the cash pools (USD) so they are not shared BTC-USD-ETH and vice versa.  
![image](https://user-images.githubusercontent.com/209308/36233097-3be950fa-1199-11e8-9f5a-87f64d624e00.png)

So, GDAX Account #1 trades my BTC-USD and GDAX account #2 trades my ETH-USD.  In a perfect world, hahah, I know, I know ... doesn't exist, but if it did: I could trade on ONE GDAX in separate pools trade all pairings to USD (i.e. LTC-USD, ETH-USD, BCH-USD, BTC-USD).  Hopefully this is were you tell me that I'm a dumbass and that is easy to do -- I would love this to be user error, but doubt it.

It should, IMHO, ONLY trade on the USD it generated from BTC Trades AND ETH should only be allowed to use the USD it got from ETH-USD trades **_BUT NEVER should the BTC-USD then ETH use mixed pool of USD proceeds.  So, for example, BTC-USD pool can't see/access the USD from USD-ETH market proceeds_** Hence I don't start today with 100 ETH and 10 BTC then they both convert 100% to USD but the next day I have 0.00 BTC AND $0.00 USD (in BTC-USD) BUT THEN there is 18.268903 ETH plus $2,623 USD (in ETH-USD) all the while the BTC-USD is now trying to do the reverse, and use that $2,623 USD to buy BTC, from the ETH-USD proceeds.

**Comment by ctubio** [comment]
morning allenhurff'''
just wanted to say that gdax is quite strict exchange, and only allows 1 connection by ip/account/apikey. but other exchanges allow multiple connection from the same ip or from the same account (with but also some without using multiple apikeys).

so, --wallet-limit makes lot of sense for hitbtc, but less sense for gdax.

**Comment by ctubio** [comment]
@Pat71 thanks for double explaining it; i totally understand your requirement and is what i wanted to develop; let me rereview it and retest it :dancer:

i just feel like need to correct one of your sentences, please let me know if you agree (maybe here is our missunderstanding):
when you say:
```
specify --wallet-limit=50 (on ETCUSD, for example) and K sets 50$ as limit, i.e. K ""sees" only 50$ and can only spent 50$.
All values (TBP, ask/bidsize%, profit, ...) relate to that value, i.e. in this example, if I specify maxasksize=10%, the maximum ask size is 5$.
``` 
i belive the currencies are wrong, cos on ETCUSD; the base is ETC, and the USD is the quote, therefore:
```

```
specify --wallet-limit=50 (on ETCUSD, for example) and K sets 50ETC as limit, i.e. K ""sees" only 50ETC and can only spent 50ETC.
All values (TBP, ask/bidsize%, profit, ...) relate to that value, i.e. in this example, if I specify maxasksize=10%, the maximum ask size is 5ETC.
``` 
do you agree?

**Comment by Pat71** [comment]
Hm, if it can be made only like this, ok. But what I really want is what I wrote:
I have a fixed budget I want to invest (like 200USDT) and I want to split this on 4 different bots. In your example, how could I split the 200$ equally on 4 bots? I would have to calculate how much ETC 50 USDT is to set the wallet size, then I would have to calculate how much LTC 50 USDT is and so on. This would be annoying...

**Comment by ctubio** [comment]
yea, same happens with EUR on BTC/EUR, and in IOTA in XMR/IOTA, same for all quote currencies
