### ISSUE TITLE
Unlock request as I have started collaboration in XMR mining project 

### ISSUE THREAD

**Issue by shahidjalally** [ctubio/Krypto-trading-bot#642]
![screenshot_2018-02-15-00-22-29](https://user-images.githubusercontent.com/30249054/36223534-8bc3e700-11e6-11e8-83cd-bc42d7d6e994.png)
Hello,
I have installed k bot server on ubuntu vds server and web gui  opened on Windows vps and started xmr mining.
Windows vps screen shot attached. I have take this screen shot from mobile phone as I'm accessing windows vps on mobile phone with Microsoft remote desktop app.

@ctubio Please tell me where I should provide you API key?

**Comment by donaldforest** [comment]
API key packed to bitcoin address which you see to unlock.

**Comment by ctubio** [comment]
thanks for your support donalforest'¡

@shahidjalally im sorry i cannot unlock the api key because the XMR miner was executed, many users execute it as a way to say "thanks", but is not a reason to unlock the api key.

please consider to make a PR (and let me know the btc payment address you want me unlock) or unlock it yourself after making the payment to the displayed btc payment address,

in any case you dont need to tell nobody your api key, that is personal and private.
