### ISSUE TITLE
gdax cancel replace order quickly

### ISSUE THREAD

**Issue by machard** [ctubio/Krypto-trading-bot#656]
Hello,

I was wondering if you solved the following problem on your side:
When using the fix api, if you place, cancel, wait for the confirmation and replace quickly an order you may get an "insufficient fund" error. I think it's because the cancel event is sent before the settlement is really done. And per their doc the funds are held until settlement is done.
I reduce the occurence of this by keeping more balance than i use in my open orders but i still have that issue. less but still occurring.
Did you completely solve that issue ? My bot is running on us-east, as their matching engine, so i guess i go faster than their settlement process from time to time. What would help is to be notified of when the settlement is done, I've asked the support for this but did not get any response..

Thx

**Comment by ctubio** [comment]
Hello'''
since a few months ago the bot waits for orders to be in working state before attempt to cancel.
gdax holds funds longer than after closing an order IF the order was completed (on cancel gdax does not hold funds).

maybe what you experience is related to the onhold funds after order completion?

i didnt found any solution for this than slowdown the trading cycles, but since is a bad solution is not implemented; a nicer solution is to increase the available funds and collect patience when a side is almost depleted (cos no known solution yet).

**Comment by ctubio** [comment]
lets close the issue (but keep the question alive) meanwhile there is not planned a code modification :S
