### ISSUE TITLE
"No wallet data" (okex)

### ISSUE THREAD

**Issue by Pat71** [ctubio/Krypto-trading-bot#666]
I wanted to try OKEX today but I'm getting 
"NO WALLET DATA
Do a manual order first using the website of this Market!"

...but I already did some manual buys/sells (LTCUSD)...what's wrong?

The log states:
```
16:51:56.347431 GW OKEX WS Streaming channel ok_sub_spot_ltc_usd_depth_20 true.
16:51:56.348803 GW OKEX WS Streaming channel ok_sub_spot_ltc_usd_deals true.
16:51:56.375593 GW OKEX WS Streaming channel login true.
16:51:58.044667 QE Warrrrning: Unable to calculate quote, missing market data.

```

**Comment by ctubio** [comment]
at https://www.okex.com/ws_api.html says the valid values: 
`ltc_btc eth_btc etc_btc bch_btc btc_usdt eth_usdt ltc_usdt etc_usdt bch_usdt etc_eth bt1_btc bt2_btc btg_btc qtum_btc hsr_btc neo_btc gas_btc qtum_usdt hsr_usdt neo_usdt gas_usdt`

`ltc_usd` is not an option, you are missing a last letter, since is `ltc_usdt`

**Comment by ctubio** [comment]
the user error msg is not very meaningful :( will update soOn''
thanks'''
