### ISSUE TITLE
Kraken orders not match FV with pingWidth

### ISSUE THREAD

**Issue by donaldforest** [ctubio/Krypto-trading-bot#679]
Some orders filled by FV price.. This may be related that K cant cancel some orders and this orders executed when FV goes near it.

**Comment by ctubio** [comment]
Kraken market data is updated every few seconds, it doesn't have any realtime websocket; orders at FV price must be because really the order was placed at that price; consider a bigger `width` to avoid Kraken delays (but really is impossible to avoid, K and any other Kraken client will be always delayed by a few seconds and the market can move anywhere above or below your orders by that time).

**Comment by donaldforest** [comment]
Fuck! Maybe we're just wasting our energy on Kraken.. But Kraken added to K and if possible do something, will be good.

**Comment by ctubio** [comment]
will rereview order cancelation soOn at https://github.com/ctubio/Krypto-trading-bot/issues/676
