### ISSUE TITLE
Invalid calculation of market width with new model?

### ISSUE THREAD

**Issue by jpreynat** [ctubio/Krypto-trading-bot#690]
Since 04dd1e32108f6e0452d0e970d18dab601ebc01f7, the market width is sometimes invalid and even negative:

![image](https://user-images.githubusercontent.com/7927876/37848999-56b18a4c-2ed6-11e8-9ba1-bf053c84ce6a.png)

I saw that you switched to using `EventEmitter`s, so this might not be critical and simply a delay in the propagation of the values required to compute `marketWidth`.

**Comment by ctubio** [comment]
thanks for the report, thats because the top bid/ask in the array of UI levels is not always the visible top bid/ask, but instead it could be a recently deleted level (so hidden with the css effect in the UI but still present in the array of levels)

will try to calculate the width only between the visible (uptodate) top levels

**Comment by jpreynat** [comment]
👍
Le ven. 23 mars 2018 à 20:46, Carles Tubio <notifications@github.com> a
écrit :
