### ISSUE TITLE
Hey Carles are improvements in the lab :p ?

### ISSUE THREAD

**Issue by Camille92** [ctubio/Krypto-trading-bot#744]
Just wanted to check if you planned on improving the strats of the bot.

And btw I've found a bot doing something kind of similar than pingpong (and explaining it quite well), so I put the description here!

"As soon as an order completes, Cryptoblizz will create a counter order. In this example, when we have bought 1.5 ETH this will cost us 0.111154 BTC and we receive 1.5 ETH. We can now sell this 1.5 ETH as the price increases. Since we configured a sell offset of 0.6%, Cryptoblizz will sell 1.5 ETH when the price of BTC/ETH has increased 0.6%."

https://www.cryptoblizz.com/article/cryptoblizz-trading-strategies-explained/

**Comment by ctubio** [comment]
im about to finnish all basic server improvements since the migration from js; once we have lovely c++ (soOn') ima start with the UI; about the UI first i would like to optimize is the layout of settings; but later the stats could follow yea

thanks for the pingpong description; curerntly K places counter orders, but also replaces them; maybe will be nice to have an option to not replace never ever counter orders and leave them opened forever until something else triggers the removal than just market price moves

**Comment by Camille92** [comment]
Well i think the issue is more on how sometimes K will place counter (buy) orders above sell price :S

**Comment by Camille92** [comment]
Thanks for explaining the roadmap :)
