### ISSUE TITLE
[OKEX] NEW APIv3

### ISSUE THREAD

**Issue by serzhiio** [ctubio/Krypto-trading-bot#828]
https://www.okex.com/docs/en/
https://ok-public-hk.oss-cn-shenzhen.aliyuncs.com/cdn/assets/broker/apifile/doc/websocket-api-spot-en.docx

**Comment by ctubio** [comment]
i dont see any modification :S all fields are the same

**Comment by ctubio** [comment]
letz implement it

**Comment by grhangelone** [comment]
Sorry to reopen this, that there's still a problem.
For one, our old v1 API keys are not compatible with the new v3 api.
You have to create a new v3 API key with username and passphrase.

This then somehow works a little bit.
I now tested with an unregged v3 key.
Orderbook streaming works, but it went away a few times, which just might be a connection problem.
But wallet data is totally unreliable.
My wallet was shown one time and then went away after 10sec.
Now it doesn't show anymore no matter how often I restart.

Side info:
I created a new API v3 key, copied the K.sh-dist and put everything into it.
log:

`angelone@server2:~/ramdisk/K$ ./okex.sh --currency gto/eth --naked
K-trading-bot x86_64-linux-gnu 2018-10-21 00:42:16.
v0.4.10+66 (0day).
10/21 12:08:23.875717 DB loaded OK from data/okexv3.db.
10/21 12:08:23.876347 UI Warrrrning: Connected web clients will enjoy unsecure SSL encryption..
(because the private key is visible in the source!), consider --ssl-crt and --ssl-key arguments.
10/21 12:08:23.877004 UI ready at https://x.x.x.x:3004.
10/21 12:08:23.878052 DB loaded last Quoting Parameters OK.
10/21 12:08:23.878733 DB loaded 25 historical Profits.
10/21 12:08:23.879167 DB loaded 5 historical Fair Values.
10/21 12:08:23.879590 DB loaded last EWMA Values OK.
10/21 12:08:23.882822 DB loaded 418 STDEV Periods.
10/21 12:08:23.883032 GW OKEX allows client IP.
10/21 12:08:23.883221 GW OKEX setup:
- gateway: https://www.okex.com/api/
- gateway: wss://real.okex.com:10441/websocket
- autoBot: no
- symbols: gto_eth
- minTick: 0.00010000
- minSize: 0.00100000
- makeFee: 0.00000000
- takeFee: 0.00000000.
10/21 12:08:24.430196 UI 1 currently connected, last connection was from 192.168.2.96.
10/21 12:08:25.716043 QE Warrrrning: Unable to calculate quote, missing market data.
10/21 12:08:26.032198 GW OKEX WS Streaming channel ok_sub_spot_gto_eth_depth_20 true.
10/21 12:08:26.033438 GW OKEX WS Streaming channel ok_sub_spot_gto_eth_deals true.
10/21 12:08:26.038628 GW OKEX WS Streaming channel login true.
10/21 12:08:26.247837 PG Warrrrning: Unable to calculate TBP, missing wallet data.
10/21 12:08:26.287965 PG Warrrrning: Unable to calculate TBP, missing wallet data.
10/21 12:08:28.630697 PG Warrrrning: Unable to calculate TBP, missing wallet data.
10/21 12:08:29.158759 PG Warrrrning: Unable to calculate TBP, missing wallet data.
10/21 12:08:29.470816 PG Warrrrning: Unable to calculate TBP, missing wallet data.
10/21 12:08:29.987735 PG Warrrrning: Unable to calculate TBP, missing wallet data.
10/21 12:08:30.504846 PG Warrrrning: Unable to calculate TBP, missing wallet data.
10/21 12:08:31.024085 PG Warrrrning: Unable to calculate TBP, missing wallet data.
^C
10/21 12:08:31.675114 Excellent decision! Chuck Norris can binary search unsorted data.
10/21 12:08:31.676611 GW OKEX Attempting to cancel all open orders, please wait..
10/21 12:08:32.073956 GW OKEX cancel all open orders OK.
10/21 12:08:32.074173 UI 0 currently connected, last connection was from 192.168.2.96.
K exit code 0.
`

**Comment by grhangelone** [comment]
ok,  looks like the spot account endpoint changed, too.
its now GET /api/spot/v3/accounts
according to the doc file in the op.

There's now a "v3" in the url.
The changelog for the last commit only changed the GwOkEx class.
Maybe, there has to be a "v3" in some of the other places, too.

**Comment by ctubio** [comment]
thanks for the info''

okex has buggy wallet api :P
```
Dear costumer ,
I already send your issue to our tech team , please wait some time .
Best regards 

Abudu | Customer Service Representative

support@okex.com 
```

let me review it after they fix their part

**Comment by ctubio** [comment]
err, i was using `/api/account/v3/wallet`, let me use instead `/api/spot/v3/accounts`, anyway i can't wait them to fix the wallet api xD

**Comment by ctubio** [comment]
ok so `/api/spot/v3/accounts` works, but then we cannot place/cancel orders in websocket v3:
```
Dear valued user,
Sorry for late reply. There is no v3 for Websocket, could you please try it with REST API?
Thank you.
```

i dont wanna use REST API, so lets wait for them to finnish v3 someday :S

**Comment by ctubio** [comment]
im a bit tired of waiting :S will consider to remove okcoin/okex soOn otherwise..

**Comment by grhangelone** [comment]
Maybe you can substitute it for binance or bittrex then :)

**Comment by flfsbr** [comment]
I think everything is OK with OKEx api. Will you add it back to the bot?

Best.
