### ISSUE TITLE
macOS unable to open database file. after make reinstall 

### ISSUE THREAD

**Issue by jordap123** [ctubio/Krypto-trading-bot#867]
after running make reinstall  get unable to open database

**Comment by ctubio** [comment]
what database file (and path) is unable to be opened?

to see where is that file/path:
try `ls /data/db` 
try `ls /var/lib/K/db` 

next, you need to understand the problem and fix it; or remove the database file and let the app create it again for you.

**Comment by jordap123** [comment]
Yea I know where that is var/lib/k/db but after I ran make reinstall this morning it disappeared

**Comment by ctubio** [comment]
then i dont understand why, cos the Makefile dont delete database files

what it does is move the files to the new location at `/var/lib/k/db` and delete the old `/data/db` IF is empty, 

maybe the move failed in your system? :S

but if i saying "unable to open database", must be because the file exists but without permissions, or because the whole path doesnt exists.

what database file is trying to load? can you confirm if that file exists and waht are the permissions of it?

**Comment by ctubio** [comment]
`make system_install` should create the path, but make reinstall already runs make system_install

**Comment by jordap123** [comment]
yea I don’t understand either, 

I also deleted everything and started fresh , says on load if there is no db file it will create one but it doesn’t . 
Yea the move is what is failing -  im using Mac fyi. I tried running in sudo but says home-brew not allowed to run in sudo

**Comment by ctubio** [comment]
oh, thanks for the info, i know mac installer is fucked since Mojave version, cos vesion is 18.0.2 but before was 17; i took today the mac home to fix the installer, letme review also the databses ofcourse

i didnt know about the databases also failing on mac, sorry for the trouble and thanks for the report''

will hopefully fix on next commit

**Comment by ctubio** [comment]
on next run the installer will move the database files to the right folder while setting right permissions so all coOl again (:koala: hopefully)

**Comment by jordap123** [comment]
Yes I reinstalled and it worked perfectly Thanks again
