### ISSUE TITLE
cygwin

### ISSUE THREAD

**Issue by juaxix** [ctubio/Krypto-trading-bot#874]
Hello ,thanks for this software. 
Is it possible to compile and use it in Windows with VS17 or cygwin?
thanks and salute from Barcelona :)

**Comment by ctubio** [comment]
eep bon dia'¡

i didnt tested cygwin but it should work since mingw32 works everywhere cos no need any fancy dll (as opposite to compilations with cygwin as explicit target where cygwin1.dll is required)

the automatic installer doesnt work on winy, so just download manually unzip the latest tar.gz for win64 and `cp etc/K.sh.dist K.sh` as usual; the binary is standalone and will run on any winy as a native terminal app

hope it helps''

**Comment by ctubio** [comment]
to compile it, im not sure how to do it on winy, i use a Debian Buster box with compiler `x86_64-w64-mingw32` provided simply by `apt-get`

**Comment by ctubio** [comment]
about VS17 no idea, i hate it :D

**Comment by ctubio** [comment]
[![0](https://user-images.githubusercontent.com/1634027/52243398-c8991280-28d9-11e9-886e-3ed0fc9c90af.jpg)](https://www.youtube.com/watch?v=XMh1S6GAW3A)
