### ISSUE TITLE
HITBTC BUG in % order size calculation / APR : Size not working

### ISSUE THREAD

**Issue by Camille92** [ctubio/Krypto-trading-bot#878]
Hi Carles,

I'm noticing some problem with the buy and sell size in %.
It seems like you can't sell if the size of % is bigger than what you have left in the account.

(With APR size on)

Normally, it should make a sell order of the size of what's left if order size > what's left.

:)

**Comment by ctubio** [comment]
so you mean instead of placing and order of the maximum possible, is just not placing orders in that side
lemme look at it :S

**Comment by Camille92** [comment]
Yes exactly :)

**Comment by ctubio** [comment]
i can sadly reproduce it with:
```
{"aggressivePositionRebalancing":1,"aprMultiplier":2,"audio":true,"autoPositionMode":0,"bestWidth":true,"bestWidthSize":0,"bullets":2,"buySize":"0.01","buySizeMax":false,"buySizePercentage":80,"cancelOrdersAuto":true,"cleanPongsAuto":0,"delayUI":2,"ewmaSensiblityPercentage":0.5,"extraShortEwmaPeriods":12,"fvModel":0,"longEwmaPeriods":207,"mediumEwmaPeriods":102,"mode":0,"percentageValues":true,"pingAt":0,"pongAt":0,"positionDivergence":0.9,"positionDivergenceMin":0.4,"positionDivergenceMode":0,"positionDivergencePercentage":50,"positionDivergencePercentageMin":10,"profitHourInterval":0.5,"protectionEwmaPeriods":200,"protectionEwmaQuotePrice":true,"protectionEwmaWidthPing":false,"quotingEwmaTrendProtection":false,"quotingEwmaTrendThreshold":2,"quotingStdevBollingerBands":false,"quotingStdevProtection":0,"quotingStdevProtectionFactor":1,"quotingStdevProtectionPeriods":1200,"range":0.5,"rangePercentage":5,"safety":0,"sellSize":"0.01","sellSizeMax":false,"sellSizePercentage":60,"shortEwmaPeriods":56,"sopSizeMultiplier":2,"sopTradesMultiplier":2,"sopWidthMultiplier":2,"superTrades":0,"targetBasePosition":1,"targetBasePositionPercentage":50,"tradeRateSeconds":3,"tradesPerMinute":0.9,"ultraShortEwmaPeriods":3,"veryLongEwmaPeriods":408,"widthPercentage":false,"widthPing":"100","widthPingPercentage":0.205,"widthPong":"100","widthPongPercentage":0.25}
```

**Comment by ctubio** [comment]
soo after ebe3dbc orders are placed at max possible amount buut..

since forever i think [mAntonioCalculon](https://github.com/ctubio/Krypto-trading-bot/blob/master/src/lib/Krypto.ninja-data.h#L2182) (see function below that line) is wrong, most places where it uses `levels.fairValue` to transform BTC to  USD (to convert from base to quote or viceversa)  must be instead `quote.bid/ask.price`
cos the value of a quote (to be compared or substracted from the wallet values) is its own price by its own quantity; not the market fairvalue by its own quantity (that would be true if the order was about to be placed at fair value price) :S this can be the source of falsey Depleted statuses and orders denied cos no enough funds

how feels in your body?

**Comment by Camille92** [comment]
Thank you for the quick fix Carles.
You're the best 👍👍

Le mer. 13 févr. 2019 à 21:22, Carles Tubio <notifications@github.com> a
écrit :

**Comment by Camille92** [comment]
Yes true,

I've seen that on very wide market (+20% spread) where I can't because the
bot think that I don't have enough funds.

(Because I don't have enough funds at FV but o have enough at buy price).

The solution would be to use buy or sell price instead of FV.

But I don't know if it would require more computing power. :/

What do you think about that ?

Le mer. 13 févr. 2019 à 21:23, Carles Tubio <notifications@github.com> a
écrit :

**Comment by ctubio** [comment]
i just hope i dont miss any place to replace the usage of `fairValue`

will fix soOn''¡

**Comment by ctubio** [comment]
many thanks for your reports''¡! :dancer:

**Comment by Camille92** [comment]
Happy to help!

To precise, buy price for a buy order and sell price for a sell order. :)

Le mer. 13 févr. 2019 à 21:40, Carles Tubio <notifications@github.com> a
écrit :

**Comment by Camille92** [comment]
Hey Carles,

Can we reopen this issue?
I realized with the bloodbath of today that the bot still doesn't manage to sell.

This happens when the size of the sell is bigger than the amount you have in your account.

For instance, in my case, I want to make a sell order of 50% but I can't because I only have 30% in crypto in my account compared to fiat. :/

It gives me a "depleted funds" error while it should just sell all the crypto. :)

**Comment by Camille92** [comment]
We miss something like :

If buy size > available funds, then buy size = available funds.

If sell size > available funds, then sell size = available funds.

What do you think of it ?

**Comment by ctubio** [comment]
yea we have this formula, but the problem is that after rounding the final value is bigger than the available  funds (need to fix the roundings i believe)

**Comment by ctubio** [comment]
in what exchange are you having issues?

thanks''

**Comment by Camille92** [comment]
Hitbtc :(

Le lun. 25 févr. 2019 à 04:54, Carles Tubio <notifications@github.com> a
écrit :

**Comment by ctubio** [comment]
great, hitbtc have this issue of fees

you can check it going to hitbtc website, going to BTC/USD, and having USD balanace.

if you click in Buy all funs, the funds selected are not the total available, because fees are substracted even if doing a Take order.

the solution is to do the same in K, will do soOn.

**Comment by ctubio** [comment]
i really dont understand this behaviour of hitbtc, would like to send them an email, but they will not do nothing so i preffer to just do the same in K

but maybe you are interested in asking them why fees are substracted in advance from the quote quantity instead of begin subtracted (from the taker) after the order is completed? xD

**Comment by ctubio** [comment]
after next commit i think Depleted status is not possible anymore :D lets leave it a few days and i will remove Depleted codez soOn if are found to be useless

**Comment by ctubio** [comment]
i will dream with decimals the following 2 decades

**Comment by Camille92** [comment]
Fixed thank you :)
