### ISSUE TITLE
HitBTC XRP/USDT Pair Issue

### ISSUE THREAD

**Issue by MiningInMySleep** [ctubio/Krypto-trading-bot#882]
Not sure what the issue is here, but after updating to the commit that includes the HitBTC fees included, XRP/USDT seems to be unable to pull wallet data and will not trade (https://i.imgur.com/ziTcxB5.png).
I've tried deleting the database file but that didn't help.
The order book looks a little slow so maybe it's something on their websocket?

**Comment by ctubio** [comment]
oh i see, hitbtc data is not consistent :D

check:
https://api.hitbtc.com/api/2/public/symbol/XRPUSDT
https://api.hitbtc.com/api/2/public/symbol/BTCUSD

as you can see, USDT becomes USD, while USD is always USD, BTC is always BTC, and XRP is always XRP

we need to save the real currency name of hitbtc and use this for reading wallet values and place orders.
(the identifier USDT is needed for the ticker, but useless everywhere else)
(the identifier USD is misleading for the ticker, but in use everywhere else)

will recover the fix soOn'¡ (because i believe asking hitbtc to be consistent is too much effort; but you are free to try if you are patient enough'¡)

sorry for remove this fix a few days ago, i was feeling bad to have this currency override, but seems is totally mandatory :dancer: tomorrow i retry'' thanks againz''

**Comment by ctubio** [comment]
:koala: the plan is to keep in the sh config the value of `XRP/USDT`, and internally make use of what hitbtc answers (in that case `XRP/USD`)

**Comment by MiningInMySleep** [comment]
I've been messaging their support to fix their reports page (which is completely broken for me) since last year, but they are "still working on it". I don't think we can rely on them to do anything unless the whole exchange is on fire.

Thanks for the quick resolution to fix the issue!

**Comment by Camille92** [comment]
True ! XRP is the only coin you need to call "XRP/USDT", weird !
