### ISSUE TITLE
[Bitfinex] Top order sometimes behaves as Join

### ISSUE THREAD

**Issue by CooleRnax** [ctubio/Krypto-trading-bot#905]
I run several bots on bitfinex.
60% of the time everything works fine.
In Top mode order behaves as Join.
I see this bug quite often in low volume markets.
It can appear at both bid and ask sides.
This bug is confirmed both in GUI and on bitfinex exchange.

**Comment by ctubio** [comment]
consider to show some logs pointing to the error; i do not belvie that this function is called randomly (and i dont belive that modes are changed anywhere else):
https://github.com/ctubio/Krypto-trading-bot/blob/cd92d62492d26426c75aaac6d159b8bbef89113c/src/lib/Krypto.ninja-data.h#L1947-L1956

**Comment by CooleRnax** [comment]
Which debug mode I should turn on?
Previously we discussed hamelinrat problem, I believe source of the problem is the same.

**Comment by CooleRnax** [comment]
I have gathered logs:
https://www.dropbox.com/s/rbthlfh3rj5jjhp/debug_log.txt?dl=0

**Comment by CooleRnax** [comment]
A more interesting example:
https://www.dropbox.com/s/43mmr29b0ak77z5/debug_log_v2.txt?dl=0

**Comment by CooleRnax** [comment]
Issue should be reopened. Please check my logs

**Comment by xloem** [comment]
```
03/26 17:26:54.265536 DEBUG QE [H] 4:6 {"ask":{"price":0.0},"bid":{"price":0.9901399999999999,"size":3254.511836060001}}.
03/26 17:26:54.265552 DEBUG QE [I] 4:6 {"ask":{"price":0.0},"bid":{"price":0.9901300000000001,"size":3254.511836060001}}.
```
It looks like one issue here is the bot using truncation with doubles (step 'I' appears to do this), resulting in values slipping by 1 point.  Alternatives might be to round instead of truncate, or switch to a more accurate fixed-digit datatype.

**Comment by CooleRnax** [comment]
> @CooleRnax rounding branch if you want to test to see if this is the issue and can build a git branch: https://github.com/xloem/Krypto-trading-bot/tree/rounding

@xloem seems like fix doesn't work:
https://www.dropbox.com/s/e3galcm869c9vq6/debug_log_v3.txt?dl=0

**Comment by xloem** [comment]
That looks like it's still truncating.  Do you build from git or run a release for a specific platform?
If you already build from git, I think this will do it:
```
$ cd Krypto-trading-bot # enter source folder
$ git remote add xloem https://github.com/xloem/Krypto-trading-bot.git
$ git fetch xloem
$ git checkout rounding
$ make src KSRC=trading-bot
```

**Comment by CooleRnax** [comment]
seems to be working!

**Comment by CooleRnax** [comment]
@xloem This bug still happens sometimes, but much much less often.

**Comment by xloem** [comment]
When you look at the QE log, the letter code prior to each line shows which processing step is resulting in the price choice.  The list is at https://github.com/ctubio/Krypto-trading-bot/blob/master/src/lib/Krypto.ninja-data.h#L2193 .  The processing step responsible for the price is the one _on the previous line_ of the source from the quotes.debug(letter) call.
So, in your first log, the issue arose in step "I".  The previous line is `applyRoundPrice()`, so I adjusted the rounding in that function and it helped you.
Is that the same step causing the issue now, or is it a different one?
I find that often I'm getting 'join' orders because the bot is respecting the EWMA quote price., which shows up as a change in step "B".
I also found what I thought was a bug in BestWidth (step "G"), which is #915.

**Comment by CooleRnax** [comment]
@xloem here is how log looks like:
```
04/01 15:16:56.392985 DEBUG QE [?] 4:4 {"ask":{"price":0.98899,"size":3396.5275341681227},"bid":{"price":0.98103,"size":3396.5275341681227}}.
04/01 15:16:56.393034 DEBUG QE [A] 4:4 {"ask":{"price":0.98899,"size":3396.5275341681227},"bid":{"price":0.98103,"size":3396.5275341681227}}.
04/01 15:16:56.393050 DEBUG QE [B] 4:4 {"ask":{"price":0.98899,"size":3396.5275341681227},"bid":{"price":0.98103,"size":3396.5275341681227}}.
04/01 15:16:56.393063 DEBUG QE [C] 4:4 {"ask":{"price":0.98899,"size":3396.5275341681227},"bid":{"price":0.98103,"size":3396.5275341681227}}.
04/01 15:16:56.393077 DEBUG QE [D] 4:4 {"ask":{"price":0.98899,"size":3396.5275341681227},"bid":{"price":0.98103,"size":3396.5275341681227}}.
04/01 15:16:56.393091 DEBUG QE [E] 4:4 {"ask":{"price":0.98899,"size":3396.5275341681227},"bid":{"price":0.98103,"size":3396.5275341681227}}.
04/01 15:16:56.393108 DEBUG QE [F] 4:4 {"ask":{"price":0.98899,"size":3396.5275341681227},"bid":{"price":0.98103,"size":3396.5275341681227}}.
04/01 15:16:56.393130 DEBUG QE [G] 4:4 {"ask":{"price":0.98899,"size":3396.5275341681227},"bid":{"price":0.98103,"size":3396.5275341681227}}.
04/01 15:16:56.393153 DEBUG QE [H] 4:4 {"ask":{"price":0.98899,"size":3396.5275341681227},"bid":{"price":0.98103,"size":3396.5275341681227}}.
04/01 15:16:56.393173 DEBUG QE [I] 4:4 {"ask":{"price":0.98899,"size":3396.5275341681227},"bid":{"price":0.9810300000000001,"size":3396.5275341681227}}.
04/01 15:16:56.393210 DEBUG QE [J] 4:4 {"ask":{"price":0.98899,"size":3396.52753417},"bid":{"price":0.9810300000000001,"size":2693.63576037}}.
04/01 15:16:56.393240 DEBUG QE [K] 4:4 {"ask":{"price":0.98899,"size":3396.52753417},"bid":{"price":0.9810300000000001,"size":2693.63576037}}.
04/01 15:16:56.393276 DEBUG QE [L] 4:4 {"ask":{"price":0.98899,"size":3396.52753417},"bid":{"price":0.9810300000000001,"size":2693.63576037}}.
04/01 15:16:56.393290 DEBUG QE [!] 4:4 {"ask":{"price":0.98899,"size":3396.52753417},"bid":{"price":0.9810300000000001,"size":2693.63576037}}.
```

**Comment by CooleRnax** [comment]
Now it is way harder to debug because success rate is much bigger than before

**Comment by xloem** [comment]
you'll need the fairvalue and orderbook levels to debug it if the error is before those steps.  if there is something distinctive about the error, one could set a breakpoint or add a check in the code to log when that happens.

**Comment by CooleRnax** [comment]
> you'll need the fairvalue and orderbook levels to debug it if the error is before those steps. if there is something distinctive about the error, one could set a breakpoint or add a check in the code to log when that happens.

I think I will not be able to provide this

**Comment by xloem** [comment]
The code could be modified to log the information only when a top order is made as a join ... are you certain the issue is still present though?

**Comment by CooleRnax** [comment]
@xloem In very rare cases in low volume markets it is still happens.
I think success rate now is 99%+, auto cancel order option usually helps until order joins again and so on in the loop.

**Comment by CooleRnax** [comment]
It might be related to some API issues like bot believe he is the first one, but actually he is the second one.

**Comment by xloem** [comment]
@CooleRnax so, I didn't implement what I said, but I think I did enough.  Try my `rounding-test` branch:
```
$ git fetch xloem
$ git checkout -b rounding-test xloem/rounding-test
```

It adds a description to the quotes-debug output showing what step caused each order price choice change.  I also added some debug output for steps that happen before the start of price adjustment.  I'm guessing that your problems are being caused by the system respecting that the top price is not closer to the fair value than half the ping width.

**Comment by CooleRnax** [comment]
@xloem I will try to catch it report the results

**Comment by CooleRnax** [comment]
@xloem issue seems to be resolved, I don't see this problem anymore! great job!
@ctubio please merge the fix when you will have time

**Comment by CooleRnax** [comment]
@ctubio I don't see rounding fix in the commit from @xloem

**Comment by CooleRnax** [comment]
check this:
https://github.com/xloem/Krypto-trading-bot/commits/rounding

**Comment by ctubio** [comment]
err, lemme check both commits below tomorrow:
https://github.com/xloem/Krypto-trading-bot/commit/cd26f3f90839f78f1b263eefe4b686060102f0a2
https://github.com/xloem/Krypto-trading-bot/commit/8d60804d91425b9654571aaa3f9b903ffbc7cc81
thanks for the notice''

**Comment by xloem** [comment]
@ctubio to explain, as you can see from the log we discussed, the bot is getting floating-point error because of the datatype.  I found boost.multiprecision to be good enough to evade this problem in some local crypto programs I've written.  I fixed it quickly in this code by changing all truncations to rounds, so as to not magnify the error (3.99999999 -> 4.0 instead of 3.0)

**Comment by ctubio** [comment]
im sure this will not be the last time we talk about decimals but many thanks for move the issue one step forward'¡ its been a long fight xD that seems reduced finally into a single centralized function :dancer:

:koala: for now im still try hard to avoid boost

@xloem excuse me for copy&paste your mods, were small enough to be lazy enough to not use git :D

**Comment by xloem** [comment]
@ctubio thanks for handling this

Just so you know, there are standalone decimal datatype solutions too, such as https://github.com/vpiotr/decimal_for_cpp .

**Comment by ctubio** [comment]
thanks for the info'''
we started using https://github.com/vpiotr/decimal_for_cpp while migrating from nodejs but was soon removed after a few months cos i got bored of it (note before we had a little chaos instead of a single centralized function, and it was decimals truncating/rounding everywhere; i hate it so much xD)

soOn we can try to reconsider it; but if you ask me im quite happy with the current approach; im not missing a external dec lib :D (but do you feel we miss it?)

**Comment by xloem** [comment]
Eh, when I first saw the code I was surprised it didn't use decimal arithmetic, but I just did the calculation and you're right: the inaccuracies only rise above a minSize of 0.00000001 at around 100,000,000 coins, which is more than the whole supply of bitcoin.  It would make the code look more trustworthy, but the few satoshi errors it would fix would probably be unnoticeable in practice!
