### ISSUE TITLE
ccxt integration?

### ISSUE THREAD

**Issue by nonkreon** [ctubio/Krypto-trading-bot#917]
I started experimenting with zenbot because it supports Bittrex, Huobi and Kucoin (and also binance but we all know why that's outta discussion #571 ). Let's not say I didn't not like it at all, but Krypto-trading-bot is certainly the best :1st_place_medal: 

Instead of requesting to implement these exchanges one by one, what do you think of directly integrating [ccxt](https://github.com/ccxt/ccxt) into Krypto trading bot backend? We would have the ability to use hundreds of xchanges and you would never have to worry about fixing stuff if xchanges update their APIs and stuff.

**Comment by ctubio** [comment]
morning nonkreon'''
i really dont wanna get rid of the custom apis we currently have (and the ones of the future too) cos having codes at home is far better than trusting some 3rdparty library (like highcharts that [crashed](https://stackoverflow.com/questions/55459608/getting-error-while-using-highcharts-in-angular-7) because computer-says-no [yesterday](https://github.com/ctubio/Krypto-trading-bot/commit/3baedebb7a6a14b8b02d73d777b293d0e78c77ff)).

anyway i agree ccxt rocks! (like all other libs we use :D) so i will consider to add it (after study it once more); together with our custom apis, just as another gateway :S lets see if works'¡ xD

:koala: many thanks for the suggestion''

**Comment by ctubio** [comment]
just saying, as of today the highcharts issue is still opened https://github.com/highcharts/highcharts/issues/10463 (at least with high priority); i really dont wanna see lets say coinbase integration crashing for a day xDD

**Comment by ctubio** [comment]
err.. well ccxt is only native for js/php/python, and i really dont wanna wrap any language yet :S

maybe in the future to allow also to write custom lil script for the quoting engine (in lua or php or python, not js :D)

allow me to close thiz issue cos is not feasible to wrap php or python yet (need more reasons, like an injectable quoting engine) thanks'¡
