### ISSUE TITLE
SQLite error: no such table: disk.f at

### ISSUE THREAD

**Issue by Pat71** [ctubio/Krypto-trading-bot#949]
First: a big thanks to Carles for the update so K runs on (my) old debian/glibc versions!

But now I'm getting this error (running on :memory: db):

SQLite error: no such table: disk.f at DELETE FROM disk.f;INSERT INTO disk.f (id,json) VALUES(...

What's the problem?

**Comment by ctubio** [comment]
morning Pat71''''
thanks for the thanks'¡ :D

about the sqlite error, the table `f` is the table for storing QuotingParameters, so i imagine you are getting this error after clicking [Save] button in the UI; and database `disk` is the naming used while `--database :memory:` so i attempted to reproduce your issue this way but i didnt found any error; i can confirm the [Save] button works nice even with `--database :memory:`

maybe a solution for you is to delete the database file at `/var/lib/K/db/K-trading-bot.*.db`?

i had never need to delete a database file, but i dont know what is going on in your system :(

(note that nobody cares if table `f` doesnt exists, it is recreated as needed on boot, so the only possible situation to reproduce this issue is by removing table `f` manually with a external program while K is running, sine the table is created on boot, it will not be created on next save, and this error could be displayed; that is not fixable, i would just recommend to not edit the database externally while the app is running :S)

**Comment by ctubio** [comment]
:koala: feel free to comment if you still have issues'¡
