### ISSUE TITLE
Some question about probram

### ISSUE THREAD

**Issue by Jorman** [ctubio/Krypto-trading-bot#96]
Hi, I'm trying the bot from one day and I've some question. I'm noob to this word so think that like a FAQ section

I ask you, or who know, some explanation on my mistakes.

I started the bot (green button) and I'm trying to understand the option that I've to use the bot. I'm not expert so I don't touch to much around the settings. After a reading I decided to start with the Join preset on poloniex with XRP/BTC
![cattura](https://user-images.githubusercontent.com/5203988/28543964-e48a7a28-70c1-11e7-8c5a-a02a234c5dd3.PNG)
Is running from a day but till now nothing, I tried to change some but with no luck, maybe I changed the wrong settings or maybe the marked is "not adapt"?

For example here, I see
```
66.18798582
0.00463
-0.01%, -0.01%
```
I think is the 2 value of what I've if I convert in one or other value, so I've 66xrp or 0.004btc, the value below indicate the market fluctuation? Some times to up to 600% sometimes down to -67%
I also noticed that I always have a TBPHeld write and I don't know what is

Another question is about the running, I see that from the start there's some new commit but I also run the bot for usd/btc and right now is making some trade. I can start the update process or if I update the bot 
 after that the bot start from scratch and I "lose" all settings and all trade?

**Comment by ctubio** [comment]
you can run `npm run latest` to update the bot source code anytime, this will update, reinstall and restart, keeping your setting and history of trades.

about the `TBPHeld` is because the `tbp` setting and also the `pDiv` setting, you can read more about them in the MANUAL file.

hope it helps''

**Comment by Jorman** [comment]
Tnx @ctubio for your reply

I read all the manual, many and many times, but like I said I'm very noob to this argument, I understand the works of the market but some technical words are not so easy for me.

I think the main problem is that I don't know what mean "target base position". In the manual I see many times "target base position" but I don't see how to set it up or what is (I know is my limitation, I'm not expert sorry)

Do you have some advice to play of with value on market like xrp and not on usd? I'm trying but I don't want to make too damage. I'm pretty stuck because I don't know some basic info I think

**Comment by ctubio** [comment]
maybe you you enable `%` option, the `tbp` value is easy to understand.

lets say you have `%` enabled, and `50` as the value of `tbp`, in this situation you will have `50%` of BTC and `50%` of USD.


lets say you have `%` enabled, and `30` as the value of `tbp`, in this situation you will have `30%` of BTC and `70%` of USD.

so `tbp` or "target base position" is the wallet amount in the BTC side that you want the bot to try to stay with.

if you set `tbp` to 90, you are saying to the bot to not sell your BTC and to try to have as much BTC as possible always.


if you set `tbp` to 10, you are saying to the bot to sell asap your BTC and to try to have as much USD as possible always.

`pDiv` is the margin that you allow the bot to fluctuate from the `tbp` value.

a `pDiv` of 50% and `tbp` of 50% effectivelly allows the 100% of your wallet to sell or buy without any preference.

all this is true if `apMode` is set to `MANUAL`; otherwise if `apMode` is some `EWMA` you don't need to set `tbp` because will be auto calculated based on the market movement

**Comment by Jorman** [comment]
Ok, tnx for the info, so I feel you don't use `EWMA` but what happen if I put 100 or 0? Let's see I start with a pair but I don't want to collect foreign coins, for example let's take `XRP/BTC` so I can put 0 to tell to the bot that I don't want to hold `XRP`, well the bot start when is possible and don't accumulate `XRP` or the bot don't start?

Where I can find some info about this `EWMA` or to test with the pair that I've choose to see what value works best? I think your preset are already "good" but can be adjusted if one have some study behind

**Comment by ctubio** [comment]
mm i think you are looking for a google search of "Exponentially Weighted Moving Average"

all the info about what the bot is doing is displayed in the UI

**Comment by Jorman** [comment]
Tnx for the search, I'll do some research.
I'm sure that all is in the Ui, the problem for me is I'm starting so I need to understand, for that I ask, sorry if I bother you,

**Comment by ctubio** [comment]
maybe for questions not related to the source code a good idea is to join the irc channel at https://kiwiirc.com/client/irc.domirc.net:6697/?theme=cli##tradingBot

**Comment by Jorman** [comment]
Tnx, I'll when on pc to learn some, I hope :D
