### ISSUE TITLE
K is running on External IP 

### ISSUE THREAD

**Issue by Gondee** [ctubio/Krypto-trading-bot#983]
When i start K, and the webserver runs it starts on the external IP, and not my local ip. I can still access it via localhost on the hosting machine. I have this running on a VM remotely, but on the same network. How do i configure the listening IP address?

**Comment by Gondee** [comment]
ifconfig returns my proper local IP (not external)

**Comment by ctubio** [comment]
er... when you mean "external IP" you mean the outbound ip for trading? or the ip for accessing the UI?

the reported outbound ip is what the exchanges see, and is what the exchanges ban; thats why is reported

the reported UI ip is what you can use to connect to the UI, and you can use it only if your firewall/routr have the external port opened; otherwise (and concurrently) you can always use any other ip/hostname that is pointing to that machine; like localhost or 192.168.0.1 or 192.168.0.36 or 127.0.0.1 or my_custom_domain or whatever..

K just report external IPs; doesn't know nothing about your unlimited myraid of redundant ip/hostnames among all the possible networks where your computer is connected;

anyway, again, feel free to use any ip/hostname you like, it will work as long as that ip/hostname points to the machine

**Comment by ctubio** [comment]
btw, for outbound connections the title of the issue doesn't makes sense; aplications are always running locally

for inbound connections the title can only be true if the router have the port open; if you keep close the port nobody from outside will access you application no matter what
